import type jsPDF from 'jspdf';

/**
 * Shared CA-grade PDF helpers. All financial statement PDFs (sales report,
 * udhar khata, ledger, purchase register…) render the same header/footer
 * layout so the output looks like a coherent set of statements — the kind a
 * shopkeeper can hand to their accountant at tax time without embarrassment.
 *
 * Design contract:
 *   • A4 portrait (default jsPDF geometry — 210×297 mm)
 *   • 15 mm side margins
 *   • Header block occupies ~35 mm at the top of every page
 *   • Footer occupies ~15 mm at the bottom of every page
 *   • Body starts at Y=45 mm and ends at Y=277 mm
 *
 * Every helper returns the Y coordinate immediately BELOW the block it drew
 * so callers can chain positions without manual math.
 */

export interface ShopHeader {
  name: string;
  address?: string | null;
  mobile?: string | null;
  email?: string | null;
  gst?: string | null;
  pan?: string | null;
}

export const PDF_LAYOUT = {
  marginX: 15,
  headerBottomY: 45,
  footerHeight: 15,
  pageWidth: 210,
  pageHeight: 297,
  accent: [16, 122, 89] as [number, number, number],   // muted emerald — professional, not neon
  accentSoft: [232, 246, 240] as [number, number, number],
  ink: [30, 41, 59] as [number, number, number],       // slate-800 for body text
  muted: [100, 116, 139] as [number, number, number],  // slate-500 for labels
  divider: [203, 213, 225] as [number, number, number], // slate-300 for hairlines
} as const;

// ─── HEADER ────────────────────────────────────────────────────────────────
export interface HeaderLabels {
  periodLabel?: string;
  generatedLabel?: string;
  businessNameFallback?: string;
}

export function renderProfessionalHeader(
  doc: jsPDF,
  shop: ShopHeader,
  reportTitle: string,
  dateRange: string,
  labels: HeaderLabels = {},
): number {
  const L = PDF_LAYOUT.marginX;
  const R = PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginX;

  // Shop name (large, left)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...PDF_LAYOUT.ink);
  doc.text(shop.name || labels.businessNameFallback || 'Business Name', L, 15);

  // Shop meta lines under the name — address / mobile / email / GSTIN / PAN.
  // Each line only rendered when the value exists so shops without a GSTIN
  // don't get an awkward "GSTIN: -" placeholder.
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...PDF_LAYOUT.muted);
  let y = 20;
  if (shop.address) { doc.text(shop.address, L, y); y += 4; }
  const line2 = [shop.mobile ? `Mob: ${shop.mobile}` : null, shop.email || null].filter(Boolean).join('   |   ');
  if (line2) { doc.text(line2, L, y); y += 4; }
  const line3 = [shop.gst ? `GSTIN: ${shop.gst}` : null, shop.pan ? `PAN: ${shop.pan}` : null].filter(Boolean).join('   |   ');
  if (line3) { doc.text(line3, L, y); y += 4; }

  // Report title + date range block (right-aligned)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(...PDF_LAYOUT.accent);
  doc.text(reportTitle.toUpperCase(), R, 15, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...PDF_LAYOUT.muted);
  doc.text(`${labels.periodLabel || 'Period'}: ${dateRange}`, R, 20, { align: 'right' });
  doc.text(`${labels.generatedLabel || 'Generated'}: ${new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}`, R, 24, { align: 'right' });

  // Divider bar under the header — flat accent stripe.
  doc.setFillColor(...PDF_LAYOUT.accent);
  doc.rect(L, 38, R - L, 1.2, 'F');

  return PDF_LAYOUT.headerBottomY;
}

// ─── FOOTER (called once at the end for every page) ─────────────────────────
export function renderProfessionalFooter(doc: jsPDF, disclaimer?: string): void {
  const pageCount = (doc as any).internal.getNumberOfPages();
  const L = PDF_LAYOUT.marginX;
  const R = PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginX;
  const y = PDF_LAYOUT.pageHeight - 10;

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(...PDF_LAYOUT.divider);
    doc.line(L, y - 4, R, y - 4);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...PDF_LAYOUT.muted);
    if (disclaimer) doc.text(disclaimer, L, y);
    else doc.text('Generated by Vyapar Sarthi', L, y);
    doc.text(`Page ${i} of ${pageCount}`, R, y, { align: 'right' });
  }
}

// ─── SECTION TITLE ─────────────────────────────────────────────────────────
export function renderSectionTitle(doc: jsPDF, y: number, title: string): number {
  const L = PDF_LAYOUT.marginX;
  doc.setFillColor(...PDF_LAYOUT.accent);
  doc.rect(L, y, 3, 6, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...PDF_LAYOUT.ink);
  doc.text(title.toUpperCase(), L + 6, y + 4.5);
  return y + 10;
}

// ─── SUMMARY / KPI BOX ─────────────────────────────────────────────────────
export interface SummaryItem { label: string; value: string; tone?: 'default' | 'positive' | 'negative' }

export function renderSummaryBox(doc: jsPDF, y: number, items: SummaryItem[]): number {
  const L = PDF_LAYOUT.marginX;
  const W = PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginX * 2;
  const cellW = W / items.length;
  const H = 18;

  doc.setFillColor(...PDF_LAYOUT.accentSoft);
  doc.rect(L, y, W, H, 'F');
  doc.setDrawColor(...PDF_LAYOUT.accent);
  doc.setLineWidth(0.3);
  doc.rect(L, y, W, H);

  items.forEach((item, i) => {
    const cx = L + cellW * i + cellW / 2;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...PDF_LAYOUT.muted);
    doc.text(item.label.toUpperCase(), cx, y + 6, { align: 'center' });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    const tone = item.tone === 'positive' ? [22, 163, 74]
      : item.tone === 'negative' ? [220, 38, 38]
      : PDF_LAYOUT.ink;
    doc.setTextColor(tone[0], tone[1], tone[2]);
    doc.text(item.value, cx, y + 13, { align: 'center' });

    // Vertical dividers between cells
    if (i > 0) {
      doc.setDrawColor(...PDF_LAYOUT.divider);
      doc.setLineWidth(0.2);
      doc.line(L + cellW * i, y + 3, L + cellW * i, y + H - 3);
    }
  });

  doc.setLineWidth(0.2);
  return y + H + 6;
}

// ─── SIGNATURE BLOCK ───────────────────────────────────────────────────────
export function renderSignatureBlock(doc: jsPDF, y: number, customLabels?: [string, string, string]): number {
  const L = PDF_LAYOUT.marginX;
  const W = PDF_LAYOUT.pageWidth - PDF_LAYOUT.marginX * 2;
  const H = 22;
  const cellW = W / 3;
  const labels = customLabels || ['Prepared By', 'Verified By', 'Authorized Signatory'];

  doc.setDrawColor(...PDF_LAYOUT.divider);
  doc.setLineWidth(0.2);

  labels.forEach((label, i) => {
    const x = L + cellW * i;
    // Signature line — sits ~4mm above the label.
    doc.line(x + 5, y + H - 8, x + cellW - 5, y + H - 8);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...PDF_LAYOUT.muted);
    doc.text(label, x + cellW / 2, y + H - 3, { align: 'center' });
  });

  return y + H;
}

// ─── UTILITIES ─────────────────────────────────────────────────────────────
/** Uniform Indian currency format used across every table cell. */
export const fmtInr = (n: number | null | undefined): string => {
  const v = Number(n) || 0;
  return `Rs ${Math.round(v).toLocaleString('en-IN')}`;
};

/** Standard autoTable styling — pass to the `styles` prop for consistency. */
export const PROFESSIONAL_TABLE_STYLES = {
  theme: 'grid' as const,
  styles: {
    font: 'helvetica',
    fontSize: 9,
    cellPadding: 2.5,
    textColor: PDF_LAYOUT.ink as any,
    lineColor: PDF_LAYOUT.divider as any,
    lineWidth: 0.15,
  },
  headStyles: {
    fillColor: PDF_LAYOUT.accent as any,
    textColor: [255, 255, 255] as any,
    fontStyle: 'bold' as const,
    fontSize: 9,
  },
  alternateRowStyles: { fillColor: [249, 250, 251] as any },
  margin: { left: PDF_LAYOUT.marginX, right: PDF_LAYOUT.marginX },
};

/** Ensure there's at least `neededMm` free space below `y` on the current
 *  page; if not, add a fresh page and return the new starting Y. */
export function ensureRoom(doc: jsPDF, y: number, neededMm: number): number {
  const bodyEnd = PDF_LAYOUT.pageHeight - PDF_LAYOUT.footerHeight - 5;
  if (y + neededMm <= bodyEnd) return y;
  doc.addPage();
  return PDF_LAYOUT.headerBottomY;
}
