export interface MillMachinePreset {
  id: string;
  name: string;
  nameMr: string;
  nameHi: string;
  machineType: string;
  category: 'cleaning' | 'destoning' | 'milling' | 'grading' | 'sorting' | 'packing' | 'handling' | 'utility';
  categoryLabel: string;
  stageCode: 'CLEANING' | 'DESTONING' | 'MILLING' | 'GRADING' | 'SORTING' | 'PACKING' | 'GENERAL';
  defaultSpecs: string;
  description: string;
  descriptionMr: string;
  icon: string;
  isStandardLine?: boolean; // Recommended for 1-click basic mill line setup
}

export const MILL_MACHINE_PRESETS: MillMachinePreset[] = [
  // ──────────────── 1. Cleaning & Pre-Cleaning ────────────────
  {
    id: 'vibratory-pre-cleaner',
    name: 'Vibratory Pre-Cleaner',
    nameMr: 'व्हायब्रेटरी प्री-क्लिनर (Vibratory Pre-Cleaner)',
    nameHi: 'वाइब्रेटरी प्री-क्लीनर',
    machineType: 'Pre-Cleaner',
    category: 'cleaning',
    categoryLabel: 'Cleaning',
    stageCode: 'CLEANING',
    defaultSpecs: '5–10 TPH · 2 HP Motor · Double Deck Sieve',
    description: 'Removes coarse impurities, large straw, stones, and chaff before main processing.',
    descriptionMr: 'कच्च्या धान्यातून काडी-कचरा, मोठे खडे, पेंढा व धूळ वेगळे करण्यासाठी.',
    icon: '🧹',
    isStandardLine: true,
  },
  {
    id: 'fine-cleaner-aspirator',
    name: 'Fine Grain Cleaner with Air Aspiration',
    nameMr: 'फाईन ड्रम क्लिनर व एस्पिरेटर (Fine Grain Cleaner)',
    nameHi: 'फाइन ग्रेन क्लीनर और एस्पिरेटर',
    machineType: 'Fine Cleaner',
    category: 'cleaning',
    categoryLabel: 'Cleaning',
    stageCode: 'CLEANING',
    defaultSpecs: '3–6 TPH · 3 HP Motor · High-volume Aspirator Fan',
    description: 'High precision sieve separation combined with air aspiration to eliminate fine dust and husk.',
    descriptionMr: 'बारीक धूळ, तूस आणि हलका कचरा हवेच्या झोताने बाहेर काढणारा ड्रम क्लिनर.',
    icon: '🌪️',
  },
  {
    id: 'magnetic-separator',
    name: 'High Intensity Magnetic Separator',
    nameMr: 'मॅग्नेटिक सेपरेटर (Magnetic Separator)',
    nameHi: 'मैग्नेटिक सेपरेटर',
    machineType: 'Magnetic Separator',
    category: 'cleaning',
    categoryLabel: 'Cleaning',
    stageCode: 'CLEANING',
    defaultSpecs: '10,000 Gauss Rare-Earth Drum Magnet',
    description: 'Traps iron nails, wire scraps, and metallic foreign particles to protect downstream machines.',
    descriptionMr: 'धान्यातील लोखंडी खिळे, तारा व धातूचे कण वेगळे करून मशीनचे संरक्षण करते.',
    icon: '🧲',
  },

  // ──────────────── 2. Destoning ────────────────
  {
    id: 'gravity-destoner',
    name: 'Vibratory Gravity Destoner',
    nameMr: 'ग्रॅव्हिटी डेस्टोनर (Vibratory Destoner)',
    nameHi: 'ग्रेविटी डेस्टोनर',
    machineType: 'Destoner',
    category: 'destoning',
    categoryLabel: 'Destoning',
    stageCode: 'DESTONING',
    defaultSpecs: '4–8 TPH · 3 HP Motor · Negative Pressure Deck',
    description: 'Separates heavy stones, mud balls, and gravel using specific gravity fluidization deck.',
    descriptionMr: 'विशिष्ट वजनानुसार बारीक व मोठे खडे आणि मातीचे खडे पूर्णपणे वेगळे करणारे यंत्र.',
    icon: '🪨',
    isStandardLine: true,
  },
  {
    id: 'pressure-destoner',
    name: 'High-Capacity Pressure Destoner',
    nameMr: 'प्रेशर डेस्टोनर (Pressure Destoner)',
    nameHi: 'प्रेशर डेस्टोनर',
    machineType: 'Destoner',
    category: 'destoning',
    categoryLabel: 'Destoning',
    stageCode: 'DESTONING',
    defaultSpecs: '6–12 TPH · 5 HP Motor · Closed Air Loop',
    description: 'Continuous heavy-duty destoning with enclosed dust-free air circulation for large mills.',
    descriptionMr: 'मोठ्या क्षमतेच्या मिलसाठी बंदिस्त हवेच्या दाबाने खडे वेगळे करणारी सिस्टीम.',
    icon: '⚙️',
  },

  // ──────────────── 3. Dehusking & Hulling ────────────────
  {
    id: 'rubber-roll-sheller',
    name: 'Rubber Roll Paddy Dehusker / Sheller',
    nameMr: 'रबर रोल शेलर / डीहस्कर (Rubber Roll Sheller)',
    nameHi: 'रबर रोल शेलर / डीहस्कर',
    machineType: 'Dehusker / Sheller',
    category: 'milling',
    categoryLabel: 'Dehusking',
    stageCode: 'MILLING',
    defaultSpecs: '3–5 TPH · 10 HP Motor · 10" Pneumatic Rubber Rollers',
    description: 'Strips outer husk from paddy with 90%+ efficiency while minimizing broken grain percentage.',
    descriptionMr: 'धान्याचे तूस (Husk) काढून ब्राऊन राईस तयार करणारी रबर रोलर मशीन (90%+ डीहस्किंग).',
    icon: '🌾',
    isStandardLine: true,
  },
  {
    id: 'paddy-separator',
    name: 'Stainless Steel Paddy Separator',
    nameMr: 'पॅडी सेपरेटर टेबल (Paddy Separator Table)',
    nameHi: 'पैडी सेपरेटर',
    machineType: 'Paddy Separator',
    category: 'milling',
    categoryLabel: 'Dehusking',
    stageCode: 'MILLING',
    defaultSpecs: '40–60 Trays · 3 HP Motor · SS 304 Compartments',
    description: 'Separates unhusked paddy from brown rice and returns unhusked grain back to the sheller.',
    descriptionMr: 'शेलिंगनंतर उरलेले अख्खे भात आणि ब्राऊन राईस अचूक वेगळे करणारा ट्रे सेपरेटर.',
    icon: '📊',
    isStandardLine: true,
  },
  {
    id: 'emery-roller-sheller',
    name: 'Emery Roller Husker (Pulses / Dal Mill)',
    nameMr: 'एमरी रोलर शेलर / दाल मिल हस्कर (Emery Roller)',
    nameHi: 'एमरी रोलर दाल हस्कर',
    machineType: 'Dal Husker',
    category: 'milling',
    categoryLabel: 'Dehusking',
    stageCode: 'MILLING',
    defaultSpecs: '2–4 TPH · 7.5 HP Motor · Adjustable Emery Clearance',
    description: 'Specially designed for pulse dehusking (Toor, Moong, Urad, Chana dal processing).',
    descriptionMr: 'डाळ मिलसाठी तूर, मूग, उडीद आणि हरभरा डाळीची साले काढण्यासाठी एमरी रोलर.',
    icon: '🥣',
  },

  // ──────────────── 4. Milling, Whitening & Grinding ────────────────
  {
    id: 'abrasive-whitener',
    name: 'Vertical Cone Abrasive Whitener',
    nameMr: 'व्हाइटनर / पॉलिशर (Vertical Abrasive Whitener)',
    nameHi: 'वर्टिकल व्हाइटनर / पॉलिशर',
    machineType: 'Whitener',
    category: 'milling',
    categoryLabel: 'Whitening & Polishing',
    stageCode: 'MILLING',
    defaultSpecs: '3–5 TPH · 25 HP Motor · Silicon Carbide Carborundum Stone',
    description: 'Removes the bran layer from brown rice gently under controlled chamber pressure to produce white rice.',
    descriptionMr: 'ब्राऊन राईसवरून कोंडा (Bran) काढून पांढरा चमकदार तांदूळ तयार करणारी मशीन.',
    icon: '✨',
    isStandardLine: true,
  },
  {
    id: 'silky-water-polisher',
    name: 'Silky Mist Water Polisher',
    nameMr: 'सिल्की वॉटर पॉलिशर (Silky Mist Polisher)',
    nameHi: 'सिल्की वाटर पॉलिशर',
    machineType: 'Polisher',
    category: 'milling',
    categoryLabel: 'Whitening & Polishing',
    stageCode: 'MILLING',
    defaultSpecs: '3–5 TPH · 30 HP Motor · High-pressure Water Atomizer',
    description: 'Applies ultra-fine water mist friction to remove remaining bran dust and gives a glassy silk shine.',
    descriptionMr: 'अतिशय बारीक पाण्याचा फवारा मारून तांदळाला रेशमी चमक (Silk Shine) देणारे पॉलिशर.',
    icon: '💎',
  },
  {
    id: 'commercial-flour-chakki',
    name: 'Commercial Flour Chakki / Stone Atta Grinder',
    nameMr: 'कमर्शियल पीठ चक्की (Commercial Atta Chakki)',
    nameHi: 'कमर्शियल आटा चक्की',
    machineType: 'Flour Chakki',
    category: 'milling',
    categoryLabel: 'Grinding',
    stageCode: 'MILLING',
    defaultSpecs: '30"–36" Emery Stone · 15–20 HP Motor · 200–400 Kg/hr',
    description: 'Traditional stone disc grinding for premium stone-ground wheat flour, besan, and grain milling.',
    descriptionMr: 'गहू, ज्वारी, बाजरी व हरभरा डाळ दळण्यासाठी हेवी ड्युटी कमर्शियल दगडी चक्की.',
    icon: '🥣',
  },
  {
    id: 'hammer-mill-pulverizer',
    name: 'Heavy-Duty Hammer Mill Pulverizer',
    nameMr: 'हॅमर मिल पल्व्हरायझर (Hammer Mill Pulverizer)',
    nameHi: 'हैमर मिल पल्वराइजर',
    machineType: 'Hammer Mill',
    category: 'milling',
    categoryLabel: 'Grinding',
    stageCode: 'MILLING',
    defaultSpecs: '500–1000 Kg/hr · 20 HP Motor · 2800 RPM Hardened Beaters',
    description: 'High-speed pulverizing for spices, grains, corn, bran, and cattle feed ingredients.',
    descriptionMr: 'मसाले, धान्य, मका आणि कोंडा बारीक करण्यासाठी हाय-स्पीड हॅमर मिल.',
    icon: '⚡',
  },

  // ──────────────── 5. Grading & Sifting ────────────────
  {
    id: 'rotary-plan-sifter',
    name: 'Rotary Plan Sifter & Sieve Grader',
    nameMr: 'रोटरी सिफ्टर / चाळणी ग्रेडर (Rotary Plan Sifter)',
    nameHi: 'रोटरी प्लान सिफ्टर ग्रेडर',
    machineType: 'Plan Sifter',
    category: 'grading',
    categoryLabel: 'Grading',
    stageCode: 'GRADING',
    defaultSpecs: '3–6 TPH · 2 HP Motor · 4–6 Deck Stainless Sieve',
    description: 'Multi-deck gyratory sifting to classify milled grain into Head grain, Broken (Tukda), and Tips.',
    descriptionMr: 'तांदूळ/डाळीचे तुकडा, कणी आणि अख्खा दाणा यांमध्ये अचूक वर्गीकरण करणारी रोटरी चाळणी.',
    icon: '📐',
    isStandardLine: true,
  },
  {
    id: 'length-grader-cylinder',
    name: 'Length Grader (Indented Cylinder)',
    nameMr: 'लेंग्थ ग्रेडर सिलिंडर (Length Grader Indented Cylinder)',
    nameHi: 'लेंथ ग्रेडर सिलेंडर',
    machineType: 'Length Grader',
    category: 'grading',
    categoryLabel: 'Grading',
    stageCode: 'GRADING',
    defaultSpecs: '2–4 TPH · 2 HP Geared Motor · Precision Pocket Shells',
    description: 'Pocketed cylinder separation that removes broken rice grains of specific length from head rice.',
    descriptionMr: 'खिशांसारख्या पॉकेट्सद्वारे तांदळाच्या लांबीनुसार तुकडा व अख्खा तांदूळ 100% वेगळा करणारा सिलिंडर.',
    icon: '📏',
  },
  {
    id: 'thickness-grader',
    name: 'Thickness Grader',
    nameMr: 'थिकनेस ग्रेडर (Thickness Grader)',
    nameHi: 'थिकनेस ग्रेडर',
    machineType: 'Thickness Grader',
    category: 'grading',
    categoryLabel: 'Grading',
    stageCode: 'GRADING',
    defaultSpecs: '3–5 TPH · 1.5 HP Motor · Slotted Screen Cylinder',
    description: 'Separates immature, flat, and pinched grains based on grain thickness.',
    descriptionMr: 'बारीक व चपटे अपरिपक्व दाणे वेगळे करून दर्जेदार जाड दाणे वेगळे करणारे यंत्र.',
    icon: '🎯',
  },

  // ──────────────── 6. Optical Sorting ────────────────
  {
    id: 'color-sortex-machine',
    name: 'Multi-Chute Full Color Optical Sortex',
    nameMr: 'कलर सॉर्टेक्स मशीन (Color Sortex Machine)',
    nameHi: 'कलर सॉर्टेक्स मशीन',
    machineType: 'Color Sortex',
    category: 'sorting',
    categoryLabel: 'Optical Sorting',
    stageCode: 'SORTING',
    defaultSpecs: '3–5 Chutes · High-resolution RGB CCD Cameras · High-speed Ejector Valves',
    description: 'AI & optical color sorting that rejects discolored, black, yellow, chalky, and damaged grains.',
    descriptionMr: 'काळे, पिवळे, खडूळ व खराब दाणे हवेच्या जेटने (Ejector) सेकंदात उडवून 99.9% शुद्धता देणारी सॉर्टेक्स मशीन.',
    icon: '👁️',
    isStandardLine: true,
  },

  // ──────────────── 7. Packaging & Bagging ────────────────
  {
    id: 'auto-bagging-machine',
    name: 'Automatic Electronic Bagging & Weighing Scale',
    nameMr: 'ऑटोमॅटिक बॅगिंग व वजन मशीन (Auto Bagging Machine)',
    nameHi: 'ऑटोमैटिक बैगिंग मशीन',
    machineType: 'Bagging Machine',
    category: 'packing',
    categoryLabel: 'Packaging',
    stageCode: 'PACKING',
    defaultSpecs: '200–400 Bags/hr · 10–50 Kg Range · Digital Load-Cell Controller',
    description: 'Precision load-cell pneumatic bagging system for automatic 10kg, 25kg, and 50kg bag filling.',
    descriptionMr: '10kg, 25kg आणि 50kg च्या गोण्यांचे अचूक वजन करून ऑटोमॅटिक भरणारी बॅगिंग मशीन.',
    icon: '⚖️',
    isStandardLine: true,
  },
  {
    id: 'continuous-bag-stitcher',
    name: 'Conveyor Bag Stitcher & Band Sealer',
    nameMr: 'कन्व्हेयर बॅग स्टीचिंग व सीलर (Conveyor Bag Closer)',
    nameHi: 'कन्वेयर बैग स्टिचिंग मशीन',
    machineType: 'Bag Stitcher / Sealer',
    category: 'packing',
    categoryLabel: 'Packaging',
    stageCode: 'PACKING',
    defaultSpecs: '3-Meter Slat Conveyor · Heavy Duty Sewing Head · Auto Thread Cutter',
    description: 'Continuous heavy-duty bag sewing with conveyor feeding and automatic thread cutting.',
    descriptionMr: 'भरलेल्या गोण्यांची सलग शिलाई करणारी हेवी ड्युटी कन्व्हेयर स्टीचिंग मशीन.',
    icon: '🧵',
  },
  {
    id: 'form-fill-seal-pouch',
    name: 'Automatic Form-Fill-Seal Pouch Packing Machine',
    nameMr: 'ऑटोमॅटिक पाऊच पॅकिंग मशीन (Form-Fill-Seal Pouch Machine)',
    nameHi: 'ऑटोमैटिक पाउच पैकिंग मशीन',
    machineType: 'Pouch Packing Machine',
    category: 'packing',
    categoryLabel: 'Packaging',
    stageCode: 'PACKING',
    defaultSpecs: '1–5 Kg Nitrogen Flush · 30–50 Pouches/min · Touchscreen PLC',
    description: 'High speed retail pouch packing for 500g, 1kg, 2kg, and 5kg consumer branded packs.',
    descriptionMr: '1kg ते 5kg च्या ब्रँडेड पाऊचचे ऑटोमॅटिक सीलिंग व नायट्रोजन फ्लशिंग पॅकिंग.',
    icon: '📦',
  },

  // ──────────────── 8. Material Handling & Utilities ────────────────
  {
    id: 'bucket-elevator-system',
    name: 'Heavy-Duty Z-Type Bucket Elevator System',
    nameMr: 'बकेट एलेव्हेटर सिस्टीम (Bucket Elevator System)',
    nameHi: 'बकेट एलेवेटर',
    machineType: 'Bucket Elevator',
    category: 'handling',
    categoryLabel: 'Material Handling',
    stageCode: 'GENERAL',
    defaultSpecs: '5–15 TPH · Geared Motor · Food-Grade Nylon Buckets & Oil-Resistant Belt',
    description: 'Continuous vertical lifting of grain between machines with zero spillage and minimal grain breakage.',
    descriptionMr: 'धान्य एका मशीनमधून दुसऱ्या मशीनमध्ये वर उचलून नेण्यासाठी बकेट एलेव्हेटर सिस्टीम.',
    icon: '🏗️',
  },
  {
    id: 'screw-conveyor',
    name: 'Stainless Steel Screw Conveyor / Auger',
    nameMr: 'स्क्रू कन्व्हेयर (Screw Conveyor / Auger)',
    nameHi: 'स्क्रू कन्वेयर',
    machineType: 'Screw Conveyor',
    category: 'handling',
    categoryLabel: 'Material Handling',
    stageCode: 'GENERAL',
    defaultSpecs: '3–10 TPH · SS 304 Spiral Flighting · Direct Geared Drive',
    description: 'Horizontal enclosed grain, flour, and bran conveyance preventing dust leakage.',
    descriptionMr: 'कोंडा, धान्य आणि पीठ आडवे सुरक्षित वाहून नेण्यासाठी स्टेनलेस स्टील स्क्रू कन्व्हेयर.',
    icon: '🔄',
  },
  {
    id: 'dust-cyclone-blower',
    name: 'Centrifugal Dust Cyclone & High-Pressure Blower',
    nameMr: 'डस्ट सायक्लोन व एअर ब्लोअर (Dust Cyclone & Air Blower)',
    nameHi: 'डस्ट साइक्लोन और ब्लोअर',
    machineType: 'Dust Cyclone & Blower',
    category: 'utility',
    categoryLabel: 'Dust & Utility',
    stageCode: 'GENERAL',
    defaultSpecs: '5000–10000 CFM · 15 HP Blower Motor · Rotary Air-Lock Valve',
    description: 'Plant-wide aspiration and dust extraction system maintaining clean air and collecting fine bran.',
    descriptionMr: 'पूर्ण मिलमधील धूळ शोषून हवेचे शुद्धीकरण करणारा आणि कोंडा गोळा करणारा सायक्लोन.',
    icon: '💨',
  },
];
